- name: check ledger mount
  become: true
  become_user: root
  shell: df -h | grep mnt/solana-ledger
  ignore_errors: yes
  register: mount_ledger

- name: check accounts mount
  become: true
  become_user: root
  shell: df -h | grep mnt/solana-accounts
  ignore_errors: yes
  register: mount_accounts

- name: format ledger_disks with ext4
  become: true
  become_user: root
  shell: mkfs.ext4 /dev/{{ ledger_disk }}
  when: mount_ledger.rc != 0

- name: format accounts_disk with ext4
  become: true
  become_user: root
  shell: mkfs.ext4 /dev/{{ accounts_disk }}
  when: mount_accounts.rc != 0

- name: mount disks for ledger
  become: true
  become_user: root
  shell: mount /dev/{{ ledger_disk }} /mnt/solana-ledger && chown -R solana:solana /mnt/solana-ledger
  when: mount_ledger.rc != 0

- name: mount disks for snapshots
  become: true
  become_user: root
  shell: mount /dev/{{ ledger_disk }} /mnt/solana-snapshots && chown -R solana:solana /mnt/solana-snapshots
  when: mount_ledger.rc != 0

- name: mount disks for accounts
  become: true
  become_user: root
  shell: mount /dev/{{ accounts_disk }} /mnt/solana-accounts && chown -R solana:solana /mnt/solana-accounts
  when: mount_accounts.rc != 0

- name: add mounted solana_ledger to fstab
  become: true
  become_user: root
  lineinfile:
    dest: /etc/fstab
    state: present
    line: "/dev/{{ ledger_disk }}    /mnt/solana-ledger    ext4    defaults    0    1"

- name: add mounted solana_snapshots to fstab
  become: true
  become_user: root
  lineinfile:
    dest: /etc/fstab
    state: present
    line: "/dev/{{ ledger_disk }}    /mnt/solana-snapshots    ext4    defaults    0    1"

- name: add mounted solana_accounts to fstab
  become: true
  become_user: root
  lineinfile:
    dest: /etc/fstab
    state: present
    line: "/dev/{{ accounts_disk }}    /mnt/solana-accounts    ext4    defaults    0    1"
