- name: Turn off swap file
  become: true
  become_user: root
  command: "sudo swapoff /swap.img"

- name: Create new swap
  become: true
  become_user: root
  command: "sudo mkswap /dev/{{ swap_disk }}"

- name: Turn on new swap
  become: true
  become_user: root
  command: "sudo swapon /dev/{{ swap_disk }}"

- name: swap check
  become: true
  become_user: root
  ignore_errors: yes
  shell: swapon -show | grep /dev/{{ swap_disk }}
  register: swap_check

- name: format swap_disk with ext4
  become: true
  become_user: root
  shell: mkfs.ext4 /dev/{{ swap_disk }}

- name: add swap_disk to fstab
  become: true
  become_user: root
  lineinfile:
    dest: /etc/fstab
    state: present
    line: "/dev/{{ swap_disk }}  none  swap  sw  0  0"


